name: Manual Hello Workflow

# This allows manual trigger
on:
  push: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build step
        run: echo "Hello, ${{ secrets.DOCKER_PASSWORD }}"
 
