name: GitHub Action Demo

on:
  push:

jobs:
  action-demo:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print index.html file
        run: cat index.html
 
