name: Manual Hello Workflow

# This allows manual trigger
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "This Line One"
          echo "This Is Line Two"
